pid /tmp/nginx/nginx.pid;
error_log /dev/stderr notice;

events {}

http {
    access_log /dev/stdout;
    client_body_temp_path /tmp/nginx/client_body;
    proxy_temp_path /tmp/nginx/proxy;
    fastcgi_temp_path /tmp/nginx/fastcgi;
    uwsgi_temp_path /tmp/nginx/uwsgi;
    scgi_temp_path /tmp/nginx/scgi;
    underscores_in_headers on;
    include /var/config/rementor/nginx/*.conf;
}
