package services

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/thiagojdb/rementor/internal/models"
	"github.com/thiagojdb/rementor/internal/validation"
)

func cloneSession(source *models.RoutingSession) *models.RoutingSession {
	if source == nil {
		return nil
	}
	copy := *source
	copy.Baseline = append([]models.ApplicationConfig(nil), source.Baseline...)
	for i := range copy.Baseline {
		copy.Baseline[i].Aliases = append([]string(nil), source.Baseline[i].Aliases...)
		copy.Baseline[i].RoutePattern = cloneStringPtr(source.Baseline[i].RoutePattern)
	}
	return &copy
}

// ResolveSession never falls back to the environment when a selector is stale.
func (r *Registry) ResolveSession(environment, session string) (string, error) {
	if session == "" {
		return environment, nil
	}
	ws := r.GetWorkspaceView(session)
	if ws == nil || ws.Session == nil {
		return "", fmt.Errorf("routing session not found: %s", session)
	}
	if environment != ws.Session.EnvironmentID && environment != ws.WorkspaceID {
		return "", fmt.Errorf("session %q belongs to environment %q, not %q", session, ws.Session.EnvironmentID, environment)
	}
	return ws.WorkspaceID, nil
}

const maxSessionHostPrefixLength = 30

func normalizedSessionHostPrefix(value string) string {
	prefix := models.NormalizeIdentityToken(value)
	if len(prefix) > maxSessionHostPrefixLength {
		prefix = strings.TrimRight(prefix[:maxSessionHostPrefixLength], "-")
	}
	return prefix
}

func isLegacySessionSuffix(value string) bool {
	if len(value) != 10 {
		return false
	}
	for _, r := range value {
		if !strings.ContainsRune("0123456789abcdef", r) {
			return false
		}
	}
	return true
}

// routingSessionHostPrefix keeps the public hostname independent from the
// opaque session ID. Name is used as a compatibility fallback for sessions
// created before HostPrefix was stored.
func routingSessionHostPrefix(ws *models.Workspace) string {
	if ws == nil || ws.Session == nil {
		return ""
	}
	if prefix := normalizedSessionHostPrefix(ws.Session.HostPrefix); prefix != "" {
		return prefix
	}
	if ws.Name != nil {
		if prefix := normalizedSessionHostPrefix(*ws.Name); prefix != "" {
			return prefix
		}
	}
	id := strings.TrimSpace(ws.WorkspaceID)
	if cut := strings.LastIndex(id, "-"); cut > 0 && isLegacySessionSuffix(id[cut+1:]) {
		id = id[:cut]
	}
	return normalizedSessionHostPrefix(id)
}

func sessionHostname(prefix, inheritedHost string) string {
	prefix = normalizedSessionHostPrefix(prefix)
	inheritedHost = strings.ToLower(strings.TrimSpace(strings.TrimSuffix(inheritedHost, ".")))
	if prefix == "" || inheritedHost == "" {
		return inheritedHost
	}
	return prefix + "." + inheritedHost
}

// legacySessionAppHost identifies the opaque hostnames generated by the first
// session implementation so they can be migrated without changing explicit
// session overrides.
func legacySessionAppHost(appID, sessionID string) string {
	sum := sha256.Sum256([]byte(appID))
	return "app-" + hex.EncodeToString(sum[:5]) + "." + sessionID + ".localhost"
}

func sessionBaseline(base *models.Workspace, hostPrefix string) []models.ApplicationConfig {
	apps := applicationConfigs(base.Applications)
	for i := range apps {
		a := &apps[i]
		if a.ServiceID == "" {
			a.ServiceID = a.CanonicalAppID()
		}
		if a.Health == "" {
			a.Health = models.DefaultHealthEndpoint
		}
		// Pin actual legacy ingress semantics as explicit metadata before persisting.
		a.PublicPath = a.IngressPath()
		a.Path = a.PublicPath
		a.UpstreamContext = a.BackendContextPath()
		a.Context = a.UpstreamContext
		a.LegacyPublicPath = false
		a.LegacyUpstreamContext = false
		a.Port = 0
		a.Active = false
		a.Route = models.RouteState{}
		a.LastOperation = nil
		if a.Domain != "" {
			a.Domain = sessionHostname(hostPrefix, a.Domain)
		}
	}
	return apps
}

func sessionHostPrefixInUse(workspaces []*models.Workspace, environment, prefix, exceptID string) bool {
	for _, workspace := range workspaces {
		if workspace.WorkspaceID == exceptID || workspace.Session == nil || workspace.Session.EnvironmentID != environment {
			continue
		}
		if routingSessionHostPrefix(workspace) == prefix {
			return true
		}
	}
	return false
}

func (r *Registry) CreateRoutingSession(environment, name, correlation string) (*models.Workspace, error) {
	name = strings.TrimSpace(name)
	if name == "" || len(name) > 120 {
		return nil, fmt.Errorf("session name must contain 1–120 characters")
	}
	slug := normalizedSessionHostPrefix(name)
	if err := validation.Identifier("session name", slug); err != nil {
		return nil, err
	}
	id := slug + "-" + strings.TrimPrefix(newOperationID("s"), "s-")[:10]
	var result *models.Workspace
	_, err := r.mutate(true, func(candidate *[]*models.Workspace) error {
		base := findWorkspace(*candidate, environment)
		if base == nil {
			return fmt.Errorf("environment not found: %s", environment)
		}
		if base.Session != nil || base.IsLocalApps() {
			return fmt.Errorf("sessions require a routing environment")
		}
		if findWorkspace(*candidate, id) != nil {
			return fmt.Errorf("session ID collision; retry creation")
		}
		if sessionHostPrefixInUse(*candidate, environment, slug, "") {
			return fmt.Errorf("a session named %q already exists in environment %q", name, environment)
		}
		localDomain := sessionHostname(slug, base.GetLocalDomain())
		if err := validation.LocalHostname(localDomain); err != nil {
			return fmt.Errorf("session hostname: %w", err)
		}
		baseline := sessionBaseline(base, slug)
		result = &models.Workspace{WorkspaceID: id, Type: models.WorkspaceTypeRouting, Name: &name, Color: cloneStringPtr(base.Color),
			RoutingConfig: &models.RoutingConfig{Mode: "path-based", LocalDomain: localDomain, DefaultRemoteBaseURL: base.GetDefaultRemoteBaseURL()},
			Session:       &models.RoutingSession{EnvironmentID: environment, HostPrefix: slug, BaselineVersion: base.Route.RouteVersion, CreatedAt: time.Now().UTC(), BaselineRemoteURL: base.GetDefaultRemoteBaseURL(), Baseline: baseline}}
		result.Applications = applicationsFromConfigs(result, baseline)
		result.SetDefaults()
		for _, a := range result.Applications {
			a.InitializeRuntime()
		}
		r.applyOperation(result, nil, r.beginOperation("upsert", correlation))
		*candidate = append(*candidate, result)
		return nil
	}, r.workspaceStore().ReplaceWorkspaces)
	if err != nil {
		return nil, err
	}
	return r.GetWorkspaceView(id), nil
}

// SessionRefresh describes exactly what a preview will apply. Its token covers
// both sides of the three-way merge so concurrent edits invalidate the preview.
type SessionRefresh struct {
	Workspace *models.Workspace `json:"workspace"`
	Changes   []string          `json:"changes"`
	Conflicts []string          `json:"conflicts"`
	Token     string            `json:"token"`
}

func refreshSession(workspaces []*models.Workspace, id string) (SessionRefresh, error) {
	ws := findWorkspace(workspaces, id)
	if ws == nil || ws.Session == nil {
		return SessionRefresh{}, fmt.Errorf("routing session not found: %s", id)
	}
	base := findWorkspace(workspaces, ws.Session.EnvironmentID)
	if base == nil {
		return SessionRefresh{}, fmt.Errorf("session environment no longer exists")
	}
	out := SessionRefresh{Workspace: cloneWorkspace(ws), Changes: []string{}, Conflicts: []string{}}
	fresh := sessionBaseline(base, routingSessionHostPrefix(ws))
	payload, _ := json.Marshal(struct {
		Revision uint64
		Session  *models.RoutingSession
		Apps     []models.ApplicationConfig
		Remote   string
		Fresh    []models.ApplicationConfig
	}{ws.Route.RouteVersion, ws.Session, applicationConfigs(ws.Applications), base.GetDefaultRemoteBaseURL(), fresh})
	digest := sha256.Sum256(payload)
	out.Token = hex.EncodeToString(digest[:])
	oldByID := map[string]models.ApplicationConfig{}
	newByID := map[string]models.ApplicationConfig{}
	for _, a := range ws.Session.Baseline {
		oldByID[a.ID] = a
	}
	for _, a := range fresh {
		newByID[a.ID] = a
	}
	current := applicationConfigs(ws.Applications)
	merged := make([]models.ApplicationConfig, 0, len(current))
	seen := map[string]bool{}
	for _, a := range current {
		seen[a.ID] = true
		old, inherited := oldByID[a.ID]
		next, exists := newByID[a.ID]
		if !inherited {
			if exists {
				out.Conflicts = append(out.Conflicts, a.ID+": new environment application conflicts with session registration")
			}
			merged = append(merged, a)
			continue
		}
		if !exists {
			// Even a local port registration is intentional work: never discard it.
			if !sameSessionConfig(a, old) {
				out.Conflicts = append(out.Conflicts, a.ID+": removed from environment but customized in session")
				merged = append(merged, a)
			} else {
				out.Changes = append(out.Changes, a.ID+": removed from environment")
			}
			continue
		}
		before := a
		av, ov, nv := reflect.ValueOf(&a).Elem(), reflect.ValueOf(old), reflect.ValueOf(next)
		for i := 0; i < av.NumField(); i++ {
			field := av.Type().Field(i).Name
			switch field {
			case "Port", "Active", "Route", "LastOperation":
				continue
			}
			if reflect.DeepEqual(av.Field(i).Interface(), ov.Field(i).Interface()) {
				av.Field(i).Set(nv.Field(i))
			}
		}
		if !sameSessionConfig(before, a) {
			out.Changes = append(out.Changes, a.ID+": inherited metadata updated")
		}
		merged = append(merged, a)
	}
	for _, a := range fresh {
		if seen[a.ID] {
			continue
		}
		if _, existed := oldByID[a.ID]; existed {
			continue
		} // preserve session deletions
		merged = append(merged, a)
		out.Changes = append(out.Changes, a.ID+": added from environment")
	}
	if ws.GetDefaultRemoteBaseURL() == ws.Session.BaselineRemoteURL {
		out.Workspace.RoutingConfig.DefaultRemoteBaseURL = base.GetDefaultRemoteBaseURL()
		if ws.GetDefaultRemoteBaseURL() != base.GetDefaultRemoteBaseURL() {
			out.Changes = append(out.Changes, "default remote URL updated")
		}
	}
	if out.Workspace.RoutingConfig == nil {
		out.Workspace.RoutingConfig = &models.RoutingConfig{Mode: "path-based"}
	}
	localDomain := sessionHostname(routingSessionHostPrefix(ws), base.GetLocalDomain())
	if out.Workspace.RoutingConfig.LocalDomain != localDomain {
		out.Workspace.RoutingConfig.LocalDomain = localDomain
		out.Changes = append(out.Changes, "session hostname updated")
	}
	out.Workspace.Applications = applicationsFromConfigs(out.Workspace, merged)
	// The ordinary editor preserves omitted patterns. Here the three-way merge
	// has already decided whether an inherited pattern was removed.
	for i, a := range out.Workspace.Applications {
		a.RoutePattern = cloneStringPtr(merged[i].RoutePattern)
		a.StripOrigin = merged[i].StripOrigin
	}
	out.Workspace.Session.Baseline = fresh
	out.Workspace.Session.BaselineVersion = base.Route.RouteVersion
	out.Workspace.Session.BaselineRemoteURL = base.GetDefaultRemoteBaseURL()
	out.Workspace.SetDefaults()
	for _, a := range out.Workspace.Applications {
		a.InitializeRuntime()
	}
	projected := cloneWorkspaces(workspaces)
	for i, w := range projected {
		if w.WorkspaceID == id {
			projected[i] = out.Workspace
		}
	}
	if err := validateWorkspaces(projected); err != nil {
		out.Conflicts = append(out.Conflicts, err.Error())
	}
	for _, c := range RouteConflicts(out.Workspace) {
		if !c.Intentional {
			out.Conflicts = append(out.Conflicts, c.Reason)
		}
	}
	return out, nil
}

func sessionHostPrefixWithLegacySuffix(prefix, sessionID string) string {
	sum := sha256.Sum256([]byte(sessionID))
	suffix := hex.EncodeToString(sum[:3])
	maxBaseLength := maxSessionHostPrefixLength - len(suffix) - 1
	if len(prefix) > maxBaseLength {
		prefix = strings.TrimRight(prefix[:maxBaseLength], "-")
	}
	if prefix == "" {
		return suffix
	}
	return prefix + "-" + suffix
}

func inheritedApplicationDomains(workspace *models.Workspace) map[string]string {
	result := make(map[string]string, len(workspace.Applications))
	for _, app := range workspace.Applications {
		result[models.NormalizeIdentityToken(app.CanonicalAppID())] = app.Domain
	}
	return result
}

func migrateInheritedApplicationHost(domain, appID, sessionID, hostPrefix, inheritedDomain string) (string, bool) {
	if inheritedDomain == "" {
		return domain, false
	}
	legacy := legacySessionAppHost(appID, sessionID)
	if !strings.EqualFold(domain, legacy) && !strings.EqualFold(domain, inheritedDomain) {
		return domain, false
	}
	next := sessionHostname(hostPrefix, inheritedDomain)
	return next, next != domain
}

// migrateSessionHostnames converts opaque legacy session hostnames into a
// readable prefix followed by the inherited parent hostname. Explicit
// application hostname overrides are retained.
func migrateSessionHostnames(workspaces []*models.Workspace) bool {
	changed := false
	usedPrefixes := make(map[string]map[string]struct{})
	for _, workspace := range workspaces {
		if workspace.Session == nil {
			continue
		}
		environment := workspace.Session.EnvironmentID
		prefix := routingSessionHostPrefix(workspace)
		if prefix == "" {
			continue
		}
		if usedPrefixes[environment] == nil {
			usedPrefixes[environment] = make(map[string]struct{})
		}
		if _, exists := usedPrefixes[environment][prefix]; exists {
			prefix = sessionHostPrefixWithLegacySuffix(prefix, workspace.WorkspaceID)
		}
		usedPrefixes[environment][prefix] = struct{}{}
		if workspace.Session.HostPrefix != prefix {
			workspace.Session.HostPrefix = prefix
			changed = true
		}

		base := findWorkspace(workspaces, environment)
		if base == nil || base.IsLocalApps() {
			continue
		}
		if workspace.RoutingConfig != nil {
			localDomain := sessionHostname(prefix, base.GetLocalDomain())
			if workspace.RoutingConfig.LocalDomain != localDomain {
				workspace.RoutingConfig.LocalDomain = localDomain
				changed = true
			}
		}
		parentDomains := inheritedApplicationDomains(base)
		for i := range workspace.Session.Baseline {
			app := &workspace.Session.Baseline[i]
			inheritedDomain := parentDomains[models.NormalizeIdentityToken(app.CanonicalAppID())]
			if next, migrated := migrateInheritedApplicationHost(app.Domain, app.CanonicalAppID(), workspace.WorkspaceID, prefix, inheritedDomain); migrated {
				app.Domain = next
				changed = true
			}
		}
		for _, app := range workspace.Applications {
			inheritedDomain := parentDomains[models.NormalizeIdentityToken(app.CanonicalAppID())]
			if next, migrated := migrateInheritedApplicationHost(app.Domain, app.CanonicalAppID(), workspace.WorkspaceID, prefix, inheritedDomain); migrated {
				app.Domain = next
				changed = true
			}
		}
	}
	return changed
}

func sameSessionConfig(a, b models.ApplicationConfig) bool {
	a.RouteOverrideSet = false
	b.RouteOverrideSet = false
	a.Aliases = a.NormalizedAliases()
	b.Aliases = b.NormalizedAliases()
	a.Route = models.RouteState{}
	b.Route = models.RouteState{}
	a.LastOperation = nil
	b.LastOperation = nil
	return reflect.DeepEqual(a, b)
}

func (r *Registry) RefreshRoutingSession(id, token, correlation string, apply bool) (SessionRefresh, error) {
	if !apply {
		return refreshSession(r.workspaceSnapshot(), id)
	}
	var result SessionRefresh
	_, err := r.mutate(true, func(candidate *[]*models.Workspace) error {
		preview, err := refreshSession(*candidate, id)
		if err != nil {
			return err
		}
		if token == "" || token != preview.Token {
			return fmt.Errorf("session refresh preview is stale; preview again")
		}
		if len(preview.Conflicts) > 0 {
			return fmt.Errorf("resolve refresh conflicts before applying: %s", strings.Join(preview.Conflicts, "; "))
		}
		r.applyOperation(preview.Workspace, nil, r.beginOperation("upsert", correlation))
		for i, w := range *candidate {
			if w.WorkspaceID == id {
				(*candidate)[i] = preview.Workspace
			}
		}
		result = preview
		return nil
	}, r.workspaceStore().ReplaceWorkspaces)
	return result, err
}

// EditSessionApplication composes the edit under the global mutation lock,
// preventing concurrent registrations from replacing one another's snapshot.
func (r *Registry) EditSessionApplication(id, appRef, correlation string, edit func(*models.ApplicationConfig) error, remove bool) (*models.Workspace, error) {
	_, err := r.mutate(true, func(candidate *[]*models.Workspace) error {
		ws := findWorkspace(*candidate, id)
		if ws == nil || ws.Session == nil {
			return fmt.Errorf("routing session not found: %s", id)
		}
		apps := applicationConfigs(ws.Applications)
		_, existing, lookupErr := findAppInWorkspace(ws, appRef)
		index := -1
		if lookupErr == nil {
			for i, a := range apps {
				if a.ID == existing.ID {
					index = i
					break
				}
			}
		}
		if remove {
			if index < 0 {
				return fmt.Errorf("application not found: %s", appRef)
			}
			apps = append(apps[:index], apps[index+1:]...)
		} else {
			a := models.ApplicationConfig{ID: appRef, AppID: appRef}
			if index >= 0 {
				a = apps[index]
			}
			if err := edit(&a); err != nil {
				return err
			}
			if index >= 0 {
				apps[index] = a
			} else {
				a.Active = false
				apps = append(apps, a)
			}
		}
		ws.Applications = applicationsFromConfigs(ws, apps)
		ws.SetDefaults()
		for _, a := range ws.Applications {
			a.InitializeRuntime()
		}
		r.applyOperation(ws, nil, r.beginOperation("upsert", correlation))
		return nil
	}, r.workspaceStore().ReplaceWorkspaces)
	if err != nil {
		return nil, err
	}
	return r.GetWorkspaceView(id), nil
}

// ValidateSessionHosts rejects hostname collisions involving sessions, including
// within a session. Legacy workspace-only ownership remains backward compatible.
func ValidateSessionHosts(workspaces []*models.Workspace, controlHost string) error {
	type owner struct {
		host, id string
		session  bool
	}
	owners := []owner{{strings.ToLower(controlHost), "control-plane", false}}
	for _, ws := range workspaces {
		hosts := []string{ws.GetLocalDomain()}
		for _, a := range ws.Applications {
			if a.Domain != "" {
				hosts = append(hosts, a.Domain)
			}
		}
		for _, h := range hosts {
			if h == "" {
				continue
			}
			h = strings.ToLower(h)
			for _, o := range owners {
				if !(o.session || ws.Session != nil) {
					continue
				}
				if hostsOverlap(h, o.host) {
					return fmt.Errorf("hostname %q in %q conflicts with %q in %q", h, ws.WorkspaceID, o.host, o.id)
				}
			}
			owners = append(owners, owner{h, ws.WorkspaceID, ws.Session != nil})
		}
	}
	return nil
}
func hostsOverlap(a, b string) bool {
	if a == b {
		return true
	}
	for _, pair := range [][2]string{{a, b}, {b, a}} {
		if strings.HasPrefix(pair[0], "*.") && strings.HasSuffix(pair[1], pair[0][1:]) {
			return true
		}
	}
	return false
}

// Called with either detached snapshots or the registry read lock held.
func annotateSharedEndpoints(views, all []*models.Workspace) {
	type binding struct{ scope, app string }
	byPort := map[int][]binding{}
	for _, w := range all {
		for _, a := range w.Applications {
			if a.Port > 0 {
				byPort[a.Port] = append(byPort[a.Port], binding{w.WorkspaceID, a.ID})
			}
		}
	}
	for _, w := range views {
		for _, a := range w.Applications {
			a.SharedWith = nil
			for _, b := range byPort[a.Port] {
				if b.scope != w.WorkspaceID || b.app != a.ID {
					a.SharedWith = append(a.SharedWith, b.scope+" / "+b.app)
				}
			}
		}
	}
}
